steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'build',
      '-t', 'gcr.io/${PROJECT_ID}/proto-task-queue:${COMMIT_SHA}',
      '.',
    ]
  - name: 'gcr.io/${PROJECT_ID}/proto-task-queue:${COMMIT_SHA}'
    env:
      - 'PTQ_PROJECT=${PROJECT_ID}'
